#!/bin/sh

# PROVIDE: lancache-dns
# REQUIRE: LOGIN
# KEYWORD: lancache-dns

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:$PATH

. /etc/rc.subr

name="lancache-dns"
rcvar="lancache-dns_enable"

# Load environment varibles
set -a
[ -f /usr/local/etc/lancache/lancache-dns/lancache-dns.conf ] && . /usr/local/etc/lancache/lancache-dns/lancache-dns.conf
[ -f /usr/local/etc/lancache/lancache.conf ] && . /usr/local/etc/lancache/lancache.conf
set +a

# Logic for different commands
start_cmd="lancache-dns_start"
stop_cmd="lancache-dns_stop"
restart_cmd="lancache-dns_restart"

# The prestart sequence
lancache-dns_prestart() {
    echo "Preparing LanCache environment..."

    # Path to config files
    CONFIG_FILES="/usr/local/etc/lancache/lancache.conf /usr/local/etc/lancache/monolithic/monolithic.conf /usr/local/etc/lancache/lancache-dns/lancache-dns.conf"
    # Path to hash 
    HASH_STORE="/var/db/lancache_config.sha256"
    # Make a new hash file
    CURRENT_HASH=$(cat $CONFIG_FILES 2>/dev/null | sha256 -q)
    # Check if hash file is present 
    if [ ! -f "$HASH_STORE" ]; then
            echo "No hash file detected creating empty file..."
            touch $HASH_STORE
    fi

    LAST_HASH=$(cat "$HASH_STORE" 2>/dev/null)

    # Compare hashes and run scripts if needed
    if [ "$CURRENT_HASH" != "$LAST_HASH" ]; then
            echo "First time running Lancache-BSD or detected configuration change running required scripts..."
    
            /opt/lancache/bin/dnstool.sh
            echo "$CURRENT_HASH" > "$HASH_STORE"
    else
            echo "No configuration change detected. Skipping setup scripts."
    fi
}

lancache-dns_start() {
    lancache-dns_prestart
    echo "Starting bind..."
    service named onestart
}

lancache-dns_stop() {
    echo "Stopping bind..."
    service named onestop
}

lancache-dns_restart() {
    lancache-dns_stop
    lancache-dns_start
}

load_rc_config $name
run_rc_command "$1"
